CREATE DATABASE `googleapp` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `googleapp`;
CREATE TABLE `persons` (
  `id_person` int(11) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(50) DEFAULT NULL,
  `lastname` varchar(50) DEFAULT NULL,
  `patronymic` varchar(50) DEFAULT NULL,
  `firstname_en` varchar(50) DEFAULT NULL,
  `lastname_en` varchar(50) DEFAULT NULL,
  `patronymic_en` varchar(50) DEFAULT NULL,
  `liveemail` varchar(50) DEFAULT NULL,
  `pass` varchar(16) DEFAULT NULL,
  `typeOfEmail` int(11) DEFAULT NULL COMMENT '1 - F.S\n2 - S.F\n3 - F-S\n4 - S-F\n',
  `date_live_reg` date DEFAULT NULL COMMENT '1',
  `faculty` varchar(5) DEFAULT NULL,
  `course` int(8) DEFAULT NULL,
  `groupa` varchar(50) DEFAULT NULL,
  `spec` varchar(15) DEFAULT NULL,
  `DSK` varchar(15) DEFAULT NULL,
  `msdnaa` bit(1) DEFAULT NULL,
  `office365` bit(1) DEFAULT b'0',
  `staffPost` varchar(45) DEFAULT NULL,
  `department` varchar(20) DEFAULT NULL,
  `departmentFull` varchar(100) DEFAULT NULL,
  `facultyFull` varchar(100) DEFAULT NULL,
  `expel` bit(1) DEFAULT NULL COMMENT 'отчислен',
  `numberSpec` varchar(45) DEFAULT NULL COMMENT 'Number of speciality',
  `studies` varchar(20) DEFAULT NULL COMMENT 'full-time studies\ncorrespondence course or distant education',
  `ukrainian` bit(1) DEFAULT NULL,
  `studentCard` varchar(25) DEFAULT NULL,
  `EDBO` varchar(50) DEFAULT NULL,
  `autoGenerate` bit(1) DEFAULT NULL,
  `pdf` bit(1) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `creation_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modification_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `dismiss` bit(1) DEFAULT b'0',
  `passOffice` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id_person`) USING BTREE,
  UNIQUE KEY `Email` (`liveemail`),
  UNIQUE KEY `EDBO_UNIQUE` (`EDBO`)
) ENGINE=InnoDB AUTO_INCREMENT=72086 DEFAULT CHARSET=utf8;
