CREATE DATABASE googleapp /*!40100 CHARACTER SET utf8 COLLATE utf8_bin */;
USE googleapp;
CREATE TABLE persons (
  id_person int(11) NOT NULL AUTO_INCREMENT,
  firstname varchar(50) NULL,
  lastname varchar(50) NULL,
  patronymic varchar(50) NULL,
  firstname_en varchar(50) NULL,
  lastname_en varchar(50) NULL,
  patronymic_en varchar(50) NULL,
  liveemail varchar(50) NULL,
  pass varchar(16) NULL,
  typeOfEmail int(11) NULL COMMENT '1 - F.S\n2 - S.F\n3 - F-S\n4 - S-F\n',
  date_live_reg date NULL COMMENT '1',
  faculty varchar(5) NULL,
  course int(8) NULL,
  groupa varchar(50) NULL,
  spec varchar(15) NULL,
  DSK varchar(15) NULL,
  msdnaa bit(1) NULL,
  office365 bit(1) b'0',
  staffPost varchar(45) NULL,
  department varchar(20) NULL,
  departmentFull varchar(100) NULL,
  facultyFull varchar(100) NULL,
  expel bit(1) NULL COMMENT 'отчислен',
  numberSpec varchar(45) NULL COMMENT 'Number of speciality',
  studies varchar(20) NULL COMMENT 'full-time studies\ncorrespondence course or distant education',
  ukrainian bit(1) NULL,
  studentCard varchar(25) NULL,
  EDBO varchar(50) NULL,
  autoGenerate bit(1) NULL,
  pdf bit(1) NULL,
  birthday date NULL,
  creation_time datetime NOT NULL CURRENT_TIMESTAMP,
  modification_time datetime NOT NULL '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  dismiss bit(1) b'0',
  passOffice varchar(45) NULL,
  PRIMARY KEY (id_person) USING BTREE,
  UNIQUE KEY Email (liveemail),
  UNIQUE KEY EDBO_UNIQUE (EDBO)
) ENGINE=InnoDB AUTO_INCREMENT=72086 CHARSET=utf8;
