package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DepartmentInf generated by hbm2java
 */
public class DepartmentInf  implements java.io.Serializable {


     private Integer idDepartment;
     private FacultyInf facultyInf;
     private String department;
     private String departmentFull;
     private Set<StuffInf> stuffInfs = new HashSet<StuffInf>(0);

    public DepartmentInf() {
    }

	
    public DepartmentInf(FacultyInf facultyInf, String department, String departmentFull) {
        this.facultyInf = facultyInf;
        this.department = department;
        this.departmentFull = departmentFull;
    }
    public DepartmentInf(FacultyInf facultyInf, String department, String departmentFull, Set<StuffInf> stuffInfs) {
       this.facultyInf = facultyInf;
       this.department = department;
       this.departmentFull = departmentFull;
       this.stuffInfs = stuffInfs;
    }
   
    public Integer getIdDepartment() {
        return this.idDepartment;
    }
    
    public void setIdDepartment(Integer idDepartment) {
        this.idDepartment = idDepartment;
    }
    public FacultyInf getFacultyInf() {
        return this.facultyInf;
    }
    
    public void setFacultyInf(FacultyInf facultyInf) {
        this.facultyInf = facultyInf;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getDepartmentFull() {
        return this.departmentFull;
    }
    
    public void setDepartmentFull(String departmentFull) {
        this.departmentFull = departmentFull;
    }
    public Set<StuffInf> getStuffInfs() {
        return this.stuffInfs;
    }
    
    public void setStuffInfs(Set<StuffInf> stuffInfs) {
        this.stuffInfs = stuffInfs;
    }




}


