package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FacultyInf generated by hbm2java
 */
public class FacultyInf  implements java.io.Serializable {


     private Integer idFaculty;
     private String faculty;
     private String facultyFull;
     private Set<DepartmentInf> departmentInfs = new HashSet<DepartmentInf>(0);
     private Set<SpecInf> specInfs = new HashSet<SpecInf>(0);

    public FacultyInf() {
    }

	
    public FacultyInf(String faculty, String facultyFull) {
        this.faculty = faculty;
        this.facultyFull = facultyFull;
    }
    public FacultyInf(String faculty, String facultyFull, Set<DepartmentInf> departmentInfs, Set<SpecInf> specInfs) {
       this.faculty = faculty;
       this.facultyFull = facultyFull;
       this.departmentInfs = departmentInfs;
       this.specInfs = specInfs;
    }
   
    public Integer getIdFaculty() {
        return this.idFaculty;
    }
    
    public void setIdFaculty(Integer idFaculty) {
        this.idFaculty = idFaculty;
    }
    public String getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }
    public String getFacultyFull() {
        return this.facultyFull;
    }
    
    public void setFacultyFull(String facultyFull) {
        this.facultyFull = facultyFull;
    }
    public Set<DepartmentInf> getDepartmentInfs() {
        return this.departmentInfs;
    }
    
    public void setDepartmentInfs(Set<DepartmentInf> departmentInfs) {
        this.departmentInfs = departmentInfs;
    }
    public Set<SpecInf> getSpecInfs() {
        return this.specInfs;
    }
    
    public void setSpecInfs(Set<SpecInf> specInfs) {
        this.specInfs = specInfs;
    }




}


