package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import slGal.LiveEdu.PasswordGenerator;
import slGal.LiveEdu.Translate;

/**
 * PersonInf generated by hbm2java
 */
public class PersonInf  implements java.io.Serializable {

    private static Path nameFileAlphabetic;
    
     private Integer idPerson;
     private String firstname;
     private String lastname;
     private String patronymic;
     private String iin;
     private String firstnameEn;
     private String lastnameEn;
     private String patronymicEn;
     private String emailPersonal;
     private String emailCorporate;
     private Boolean pdf;
     private String passPersonal;
     private String passCorporate;
     private Set<PersoneServicesConsultation> personeServicesConsultations = new HashSet<PersoneServicesConsultation>(0);
     private Set<StudentInf> studentInfs = new HashSet<StudentInf>(0);
     private Set<StuffInf> stuffInfs = new HashSet<StuffInf>(0);

    public PersonInf() {
    }

	
    public PersonInf(String firstname, String lastname, String iin) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.iin = iin;
    }
    public PersonInf(String firstname, String lastname, String patronymic, String iin, String firstnameEn, String lastnameEn, String patronymicEn, String emailPersonal, String emailCorporate, Boolean pdf, String passPersonal, String passCorporate, Set<PersoneServicesConsultation> personeServicesConsultations, Set<StudentInf> studentInfs, Set<StuffInf> stuffInfs) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.patronymic = patronymic;
       this.iin = iin;
       this.firstnameEn = firstnameEn;
       this.lastnameEn = lastnameEn;
       this.patronymicEn = patronymicEn;
       this.emailPersonal = emailPersonal;
       this.emailCorporate = emailCorporate;
       this.pdf = pdf;
       this.passPersonal = passPersonal;
       this.passCorporate = passCorporate;
       this.personeServicesConsultations = personeServicesConsultations;
       this.studentInfs = studentInfs;
       this.stuffInfs = stuffInfs;
    }
   
    public Integer getIdPerson() {
        return this.idPerson;
    }
    
    public void setIdPerson(Integer idPerson) {
        this.idPerson = idPerson;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPatronymic() {
        return this.patronymic;
    }
    
    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }
    public String getIin() {
        return this.iin;
    }
    
    public void setIin(String iin) {
        this.iin = iin;
    }
    public String getFirstnameEn() {
        return this.firstnameEn;
    }
    
    public void setFirstnameEn(String firstnameEn) {
        this.firstnameEn = firstnameEn;
    }
    public String getLastnameEn() {
        return this.lastnameEn;
    }
    
    public void setLastnameEn(String lastnameEn) {
        this.lastnameEn = lastnameEn;
    }
    public String getPatronymicEn() {
        return this.patronymicEn;
    }
    
    public void setPatronymicEn(String patronymicEn) {
        this.patronymicEn = patronymicEn;
    }
    public String getEmailPersonal() {
        return this.emailPersonal;
    }
    
    public void setEmailPersonal(String emailPersonal) {
        this.emailPersonal = emailPersonal;
    }
    public String getEmailCorporate() {
        return this.emailCorporate;
    }
    
    public void setEmailCorporate(String emailCorporate) {
        this.emailCorporate = emailCorporate;
    }
    public Boolean getPdf() {
        return this.pdf;
    }
    
    public void setPdf(Boolean pdf) {
        this.pdf = pdf;
    }
    public String getPassPersonal() {
        return this.passPersonal;
    }
    
    public void setPassPersonal(String passPersonal) {
        this.passPersonal = passPersonal;
    }
    public String getPassCorporate() {
        return this.passCorporate;
    }
    
    public void setPassCorporate(String passCorporate) {
        this.passCorporate = passCorporate;
    }
    
    public Set<PersoneServicesConsultation> getPersoneServicesConsultations() {
        return this.personeServicesConsultations;
    }
    
    public void setPersoneServicesConsultations(Set<PersoneServicesConsultation> personeServicesConsultations) {
        this.personeServicesConsultations = personeServicesConsultations;
    }
    public Set<StudentInf> getStudentInfs() {
        return this.studentInfs;
    }
    
    public void setStudentInfs(Set<StudentInf> studentInfs) {
        this.studentInfs = studentInfs;
    }
    public Set<StuffInf> getStuffInfs() {
        return this.stuffInfs;
    }
    
    public void setStuffInfs(Set<StuffInf> stuffInfs) {
        this.stuffInfs = stuffInfs;
    }

    public void clearPassword() {
        setPassCorporate(null);
    }
    
    public boolean generatePassword() {
        if (passCorporate == null) {            
            PasswordGenerator pswGen = new PasswordGenerator.BuilderMask()
                    .appendMask(PasswordGenerator.SYMBOLS_UPPER_ALPHABETIC_ENGLISH, 1)
                    .appendMask(PasswordGenerator.SYMBOLS_LOWER_ALPHABETIC_ENGLISH, 3)
                    .appendMask(PasswordGenerator.SYMBOLS_DIGIT, 4)
                    .build();

            setPassCorporate(pswGen.generate());
            return true;
        }else {
            return false;
        }
    } 
    
}


