package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private Integer idServices;
     private String name;
     private String serviceUrl;
     private Set<PersoneServicesConsultation> personeServicesConsultations = new HashSet<PersoneServicesConsultation>(0);

    public Services() {
    }

	
    public Services(String name, String serviceUrl) {
        this.name = name;
        this.serviceUrl = serviceUrl;
    }
    public Services(String name, String serviceUrl, Set<PersoneServicesConsultation> personeServicesConsultations) {
       this.name = name;
       this.serviceUrl = serviceUrl;
       this.personeServicesConsultations = personeServicesConsultations;
    }
   
    public Integer getIdServices() {
        return this.idServices;
    }
    
    public void setIdServices(Integer idServices) {
        this.idServices = idServices;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getServiceUrl() {
        return this.serviceUrl;
    }
    
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }
    public Set<PersoneServicesConsultation> getPersoneServicesConsultations() {
        return this.personeServicesConsultations;
    }
    
    public void setPersoneServicesConsultations(Set<PersoneServicesConsultation> personeServicesConsultations) {
        this.personeServicesConsultations = personeServicesConsultations;
    }




}


