package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import edu.hneu.googleapp.utill.StringExt;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;
import slGal.LiveEdu.DB.DB;
import slGal.LiveEdu.DB.HibernateUtil;
import slGal.LiveEdu.ORM.PersonInf;

/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private Integer idServices;
     private String name;
     private String serviceUrl;
     private Set<PersonInf> persones = new HashSet<PersonInf>(0);

    public Services() {
    }

	
    public Services(String name, String serviceUrl) {
        this.name = name;
        this.serviceUrl = serviceUrl;
    }
    public Services(String name, String serviceUrl, Set<PersonInf> person) {
       this.name = name;
       this.serviceUrl = serviceUrl;
       this.persones = person;
    }
   
    public Integer getIdServices() {
        return this.idServices;
    }
    
    public void setIdServices(Integer idServices) {
        this.idServices = idServices;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getServiceUrl() {
        return this.serviceUrl;
    }
    
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }
    public Set<PersonInf> getPersones() {
        return this.persones;
    }
    
    public void setPersones(Set<PersonInf> person) {
        this.persones = person;
    }
    
    public static List<Services> getAllServices()
    {
        Session ses = HibernateUtil.currentSession();
        List<Services> listServ ;

        listServ = ses.createCriteria(Services.class).list();
        return listServ;
    }


}


