package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import org.hibernate.Session;
import slGal.LiveEdu.DB.HibernateUtil;

/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private Integer idServices;
     private String name;
     private String serviceUrl;
     private Set<PersonInf> persones = new HashSet<PersonInf>(0);

    public Services() {
    }

	
    public Services(String name, String serviceUrl) {
        this.name = name;
        this.serviceUrl = serviceUrl;
    }
    public Services(String name, String serviceUrl, Set<PersonInf> person) {
       this.name = name;
       this.serviceUrl = serviceUrl;
       this.persones = person;
    }
   
    public Integer getIdServices() {
        return this.idServices;
    }
    
    public void setIdServices(Integer idServices) {
        this.idServices = idServices;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getServiceUrl() {
        return this.serviceUrl;
    }
    
    public void setServiceUrl(String serviceUrl) {
        this.serviceUrl = serviceUrl;
    }
    public Set<PersonInf> getPersones() {
        return this.persones;
    }
    
    public void setPersones(Set<PersonInf> person) {
        this.persones = person;
    }
    
    public static List<Services> getAllServices()
    {
        Session ses = HibernateUtil.currentSession();
        List<Services> listServ ;

        listServ = ses.createCriteria(Services.class).list();
        return listServ;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 47 * hash + Objects.hashCode(this.idServices);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Services other = (Services) obj;
        if (!Objects.equals(this.idServices, other.idServices)) {
            return false;
        }
        return true;
    }


}


