package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentInf generated by hbm2java
 */
public class StudentInf  implements java.io.Serializable {


     private Integer idStudent;
     private PersonInf personInf;
     private SpecInf specInf;
     private boolean ukrainian;
     private boolean studies;
     private Date dateLiveReg;
     private String edbo;
     private String studentCard;
     private String group;
     private Date createTime;
     private Date updateTime;

    public StudentInf() {
    }

	
    public StudentInf(PersonInf personInf, SpecInf specInf, boolean ukrainian, boolean studies, Date dateLiveReg, String edbo, String studentCard, String group) {
        this.personInf = personInf;
        this.specInf = specInf;
        this.ukrainian = ukrainian;
        this.studies = studies;
        this.dateLiveReg = dateLiveReg;
        this.edbo = edbo;
        this.studentCard = studentCard;
        this.group = group;
    }
    public StudentInf(PersonInf personInf, SpecInf specInf, boolean ukrainian, boolean studies, Date dateLiveReg, String edbo, String studentCard, String group, Date createTime, Date updateTime) {
       this.personInf = personInf;
       this.specInf = specInf;
       this.ukrainian = ukrainian;
       this.studies = studies;
       this.dateLiveReg = dateLiveReg;
       this.edbo = edbo;
       this.studentCard = studentCard;
       this.group = group;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public Integer getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(Integer idStudent) {
        this.idStudent = idStudent;
    }
    public PersonInf getPersonInf() {
        return this.personInf;
    }
    
    public void setPersonInf(PersonInf personInf) {
        this.personInf = personInf;
    }
    public SpecInf getSpecInf() {
        return this.specInf;
    }
    
    public void setSpecInf(SpecInf specInf) {
        this.specInf = specInf;
    }
    public boolean isUkrainian() {
        return this.ukrainian;
    }
    
    public void setUkrainian(boolean ukrainian) {
        this.ukrainian = ukrainian;
    }
    public boolean isStudies() {
        return this.studies;
    }
    
    public void setStudies(boolean studies) {
        this.studies = studies;
    }
    public Date getDateLiveReg() {
        return this.dateLiveReg;
    }
    
    public void setDateLiveReg(Date dateLiveReg) {
        this.dateLiveReg = dateLiveReg;
    }
    public String getEdbo() {
        return this.edbo;
    }
    
    public void setEdbo(String edbo) {
        this.edbo = edbo;
    }
    public String getStudentCard() {
        return this.studentCard;
    }
    
    public void setStudentCard(String studentCard) {
        this.studentCard = studentCard;
    }
    public String getGroup() {
        return this.group;
    }
    
    public void setGroup(String group) {
        this.group = group;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}


