package slGal.LiveEdu.ORM;
// Generated 04.05.2017 21:56:35 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Projections;
import slGal.LiveEdu.DB.HibernateUtil;

/**
 * StuffInf generated by hbm2java
 */
public class StuffInf  implements java.io.Serializable {


     private Integer idStuff;
     private DepartmentInf departmentInf;
     private PersonInf personInf;
     private boolean dismiss;
     private String stuffPost;
     private Date createTime;
     private Date updateTime;

    public StuffInf() {
    }

	
    public StuffInf(DepartmentInf departmentInf, PersonInf personInf, boolean dismiss) {
        this.departmentInf = departmentInf;
        this.personInf = personInf;
        this.dismiss = dismiss;
    }
    public StuffInf(DepartmentInf departmentInf, PersonInf personInf, boolean dismiss, String stuffPost, Date createTime, Date updateTime) {
       this.departmentInf = departmentInf;
       this.personInf = personInf;
       this.dismiss = dismiss;
       this.stuffPost = stuffPost;
       this.createTime = createTime;
       this.updateTime = updateTime;
    }
   
    public Integer getIdStuff() {
        return this.idStuff;
    }
    
    public void setIdStuff(Integer idStuff) {
        this.idStuff = idStuff;
    }
    public DepartmentInf getDepartmentInf() {
        return this.departmentInf;
    }
    
    public void setDepartmentInf(DepartmentInf departmentInf) {
        this.departmentInf = departmentInf;
    }
    public PersonInf getPersonInf() {
        return this.personInf;
    }
    
    public void setPersonInf(PersonInf personInf) {
        this.personInf = personInf;
    }
    public boolean isDismiss() {
        return this.dismiss;
    }
    
    public void setDismiss(boolean dismiss) {
        this.dismiss = dismiss;
    }
    public String getStuffPost() {
        return this.stuffPost;
    }
    
    public void setStuffPost(String stuffPost) {
        this.stuffPost = stuffPost;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    
    public static List<String> getAllFaculty() {
        Session ses = HibernateUtil.currentSession();
        List<String> listFaculty = new ArrayList<>();
        Criteria cr = ses.createCriteria(FacultyInf.class);
        cr.setProjection(Projections.distinct(Projections.property("faculty")));
        cr.addOrder(Order.asc("faculty"));
        listFaculty = cr.list();
        HibernateUtil.closeSession();
        return listFaculty;
    }

    public static List<String> getAllDepartment() {
        Session ses = HibernateUtil.currentSession();
        List<String> listFaculty = new ArrayList<>();
        Criteria cr = ses.createCriteria(DepartmentInf.class);
        cr.setProjection(Projections.distinct(Projections.property("department")));
        cr.addOrder(Order.asc("department"));
        listFaculty = cr.list();
        HibernateUtil.closeSession();
        return listFaculty;
    }



}


